%%{init: {'theme': 'dark', "flowchart" : { "curve" : "basis" } } }%%
graph TD

Karaktär --> Movement
Karaktär --> Vapen

Vapen --> Skada
Vapen --> Skott

Movement --> Hopp
Movement --> Gå

Fiende --> Fiende_1
Fiende --> Fiende_2
Fiende --> Boss

Fiende_1 --> HP_1

Fiende_2 --> HP_2

Boss --> HP_3

Map --> Level_1
Map --> Level_2
Map --> Level_3
